[character]
success_symbol = '[ ➜](bold green)'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = ' [$user]($style) '
show_always = false
disabled = true

[time]
disabled = true
style = 'white bold'
format = 'at [\[ $time \]]($style) '
time_format = '%Y-%m-%d %H:%M'
